# Site settings
title: AnhTT's blog
email: 
description: "Machine Learning Journey"
baseurl: ""
url: "http://trantheanh.github.io"
github_username:  trantheanh

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
